### PR TITLE
new proxy process can inherit old established connections

### PR DESCRIPTION
**Pull request by faf5678**

### CODE REVIEW

**Comment by Sheeo** [comment]
Why was this closed?

**Comment by faf5678** [comment]
more bugs found.

**Comment by faf5678** [comment]
the bugs were really just a few lost packets when replacing the server.
the testclient will not exit in this case though, but it is nothing to worry about.
kill the proxy to force test client exit and report generation.
the number of lost packets is lower than the number of times the server
was restarted during the test run.

**Comment by Sheeo** [comment]
Okay.

**Pull request merged**
